package com.skypro.java.petshelterbot.bot;

/**
 * Possible bot states
 */

public enum BotState {
    START_STATE,
    OWNER_STATE,
    INFO_STATE,

    CALL_VOLUNTEER_STATE,
    CHAT_TO_VOLUNTEER_STATE,

    VOLUNTEER_STATE,

    CHOOSE_SHELTER_STATE,
    HOW_TO_ADOPT_DOG_STATE,
    HOW_TO_ADOPT_CAT_STATE,
    HOW_TO_ADOPT_STATE,

    SEND_CONTACTS_STATE,
    FILLING_CONTACTS_STATE,
    CONTACTS_SENT_STATE,

    FILLING_REPORT,
    SEND_PHOTO_STATE,
    SEND_DIET_STATE,
    SEND_HEALTH_STATE,
    SEND_BEHAVIOR_STATE,
    REPORT_FILLED_STATE
}
